version: "3.7"

services:
  app:
    build: .
    container_name: eridanus
    environment: 
      SERVER_PORT: 50051
    ports: 
      - 50051:50051
      # - 9229:9229
    volumes: 
      - .:/usr/app